### ISSUE TITLE
Collection code detection - some false positives

### ISSUE THREAD

**Issue by nickynicolson** [sav-che/TL-2#1]
Though many uppercase alphabetic codes in the collections paragraphs relate to herbarium codes, not all do. See eg `R. Brown` in this sentence: https://github.com/sav-che/TL-2/blob/8576c25dbdf95b72cd131a23078e8bb6339111b4/Authors/Abel%2C%20Clarke%20%7Bstd.%20C.%20Abel%7D.md?plain=1#L12

**Comment by sav-che** [comment]
Thanks, fixed. Codes were verified manually, but some false positives have slipped through (there will be a few false "I"s for sure). I plan to do additional pass to check single-letter codes.
