### ISSUE TITLE
Document how tl2.io is set up

### ISSUE THREAD

**Issue by nickynicolson** [sav-che/TL-2#2]
The way that this project delivers its information as (1) a github repository with tagged releases and (2) a website at [https://tl2.io](tl2.io) may be useful for others wanting to present semi-structured information online. Therefore it would be helpful to know how tl2.io is set up and populated. Could the readme file be updated with this information please?

**Comment by sav-che** [comment]
Makes sense, will do.

**Comment by sav-che** [comment]
Added a link in readme to this new section: https://github.com/sav-che/TL-2/blob/main/Front%20matter/Documentation.md#publishing
Don't know if it covers all the potential questions, please tell if something is missing.
